stackMake:	mainApplicationStack.o	popStack.o pushStack.o printStack.o
	g++ -o stackMake	mainApplicationStack.o	popStack.o	printStack.o	pushStack.o

mainApplicationStack.o:	mainApplicationStack.cpp 
	g++ -c mainApplicationStack.cpp

popStack.o:	popStack.cpp
	g++ -c popStack.cpp

printStack.o:	printStack.cpp 
	g++ -c printStack.cpp
pushStack.o:	pushStack.cpp 
	g++ -c pushStack.cpp

